language: dart
dart: ["stable", "dev"]
sudo: false
with_content_shell: true
before_script:
  - "export DISPLAY=:99.0"
  - "sh -e /etc/init.d/xvfb start"
script:
  - "pub run test -p content-shell"
  - "dartanalyzer lib/stagexl.dart"
